ALTER TABLE "StatsSnapshot"
ADD COLUMN "threeBet" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "fourBet" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "cbet" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "foldToCbet" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "MonthlyPlayerSnapshot"
ADD COLUMN "threeBet" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "fourBet" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "cbet" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "foldToCbet" DOUBLE PRECISION NOT NULL DEFAULT 0;
